export const tools = [
  // AI Image Generators
  {
    id: "z-image-turbo",
    name: "Z-Image Turbo",
    category: "Image Generation",
    url: "https://huggingface.co/spaces/mrfakename/Z-Image-Turbo",
    description: "Fast generation, no signup, Hugging Face models, unlimited daily use",
  },
  {
    id: "deepai",
    name: "DeepAI",
    category: "Image Generation",
    url: "https://deepai.org/",
    description: "Customizable styles, no signup, free tier unlimited with watermark",
  },
  {
    id: "seedream",
    name: "Seedream",
    category: "Image Generation",
    url: "https://seedream.pro/",
    description: "High-quality realistic images, no signup, unlimited but slow during peak times",
  },
  {
    id: "flux-ai",
    name: "Flux AI",
    category: "Image Generation",
    url: "https://flux-ai.io/",
    description: "Flux model based, no signup, unlimited high-res images",
  },
  {
    id: "craiyon",
    name: "Craiyon",
    category: "Image Generation",
    url: "https://www.craiyon.com/",
    description: "Simple text-to-image, no signup, unlimited but low-res in free tier",
  },
  {
    id: "ish-chat",
    name: "Ish Chat",
    category: "Image Generation",
    url: "https://ish.chat/",
    description: "Chat-based generation, no signup, unlimited creative prompts",
  },
  {
    id: "flatai",
    name: "Flat AI",
    category: "Image Generation",
    url: "https://flatai.org/ai-image-generator-free-no-signup/",
    description: "Private mode, no signup, unlimited daily 50+ images",
  },
  {
    id: "perchance",
    name: "Perchance",
    category: "Image Generation",
    url: "https://perchance.org/ai-text-to-image-generator",
    description: "Batch generation, no signup, truly unlimited, fast",
  },
  {
    id: "freegen",
    name: "FreeGen",
    category: "Image Generation",
    url: "https://freegen.app/",
    description: "High-quality, no signup, unlimited no hidden costs",
  },
  {
    id: "notegpt",
    name: "NoteGPT",
    category: "Image Generation",
    url: "https://notegpt.io/ai-image-generator",
    description: "Latest models, no signup, unlimited",
  },
  {
    id: "magicstudio",
    name: "Magic Studio",
    category: "Image Generation",
    url: "https://magicstudio.com/ai-art-generator",
    description: "Lightning fast, no signup, unlimited art styles",
  },
  {
    id: "visualgpt",
    name: "VisualGPT",
    category: "Image Generation",
    url: "https://visualgpt.io/ai-image-generator",
    description: "Dreamy images, no signup, free quick generation",
  },
  {
    id: "imagefree",
    name: "ImageFree",
    category: "Image Generation",
    url: "https://imagefree.org/",
    description: "Truly unlimited, no signup, high-res no credits",
  },
  {
    id: "freeforai",
    name: "FreeForAI",
    category: "Image Generation",
    url: "https://draw.freeforai.com/",
    description: "FLUX.1-Dev based, no registration, unlimited",
  },
  {
    id: "upsampler",
    name: "Upsampler",
    category: "Image Generation",
    url: "https://upsampler.com/free-image-generator-no-signup",
    description: "Multi-models, no signup, unlimited daily",
  },
  {
    id: "aifreeforever",
    name: "AIFreeForever",
    category: "Image Generation",
    url: "https://aifreeforever.com/",
    description: "1000+ tools, no signup, unlimited image + other tools",
  },
  {
    id: "nightcafe",
    name: "NightCafe",
    category: "Image Generation",
    url: "https://creator.nightcafe.studio/ai-image-generator",
    description: "Free credits, models, limited free but unlimited prompts",
  },
  {
    id: "deepdream",
    name: "DeepDream",
    category: "Image Generation",
    url: "https://deepdreamgenerator.com/generate",
    description: "Good quality, limited free but unlimited experiments",
  },
  {
    id: "pixelbin",
    name: "PixelBin",
    category: "Image Generation",
    url: "https://www.pixelbin.io/ai-tools/video-generator",
    description: "Studio-quality, no signup, unlimited text-to-image",
  },
  {
    id: "raphaelai",
    name: "Raphael AI",
    category: "Image Generation",
    url: "https://raphaelai.org/",
    description: "Fast unlimited, no limits, multi-model",
  },
  {
    id: "midgenai",
    name: "MidGenAI",
    category: "Image Generation",
    url: "https://www.midgenai.com/text-to-image",
    description: "Realistic, no watermark, unlimited free",
  },
  {
    id: "muryou",
    name: "Muryou",
    category: "Image Generation",
    url: "https://muryou-aigazou.com/",
    description: "No login, multilingual, unlimited Japanese styles",
  },
  {
    id: "loboforge",
    name: "LoboForge",
    category: "Image Generation",
    url: "https://loboforge.com/",
    description: "Free supergroups, unlimited image, community-based",
  },
  {
    id: "fluidfit",
    name: "Fluidfit",
    category: "Image Generation",
    url: "https://fluidfit.ai/",
    description: "100+ models, free credits unlimited requests",
  },
  {
    id: "nsfwlover",
    name: "NSFW Lover",
    category: "Image Generation",
    url: "https://nsfwlover.com/nsfw-ai-image-generator",
    description: "NSFW allowed, Flux/Z-Image, unlimited no limit",
  },
  {
    id: "pixelbin-core",
    name: "PixelBin Core",
    category: "Image Generation",
    url: "https://pixelbin.io/",
    description: "Image tools + generation, no signup, unlimited",
  },
  {
    id: "google-imagefx",
    name: "Google ImageFX",
    category: "Image Generation",
    url: "https://labs.google/fx/tools/image-fx",
    description: "Free labs, no signup, unlimited image models",
  },
  {
    id: "bing-creator",
    name: "Bing Image Creator",
    category: "Image Generation",
    url: "https://www.bing.com/images/create",
    description: "Microsoft account, free unlimited, high quality",
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    category: "Image Generation",
    url: "https://www.canva.com/ai-image-generator",
    description: "Free tier, no watermark, integrated editing",
  },
  {
    id: "gemini-ai",
    name: "Gemini",
    category: "Image Generation",
    url: "https://gemini.google.com/",
    description: "Text + image, free Google account, unlimited",
  },
  {
    id: "arena-ai",
    name: "Arena",
    category: "Image Generation",
    url: "https://arena.ai/image",
    description: "Model comparison, unlimited voting + generation",
  },

  // AI Image Editing Tools
  {
    id: "toolfk-remove-text",
    name: "ToolFK Remove Text",
    category: "Image Editing",
    url: "https://www.toolfk.com/tools/ai-remove-text-from-image.html",
    description: "Instant free, no signup, unlimited",
  },
  {
    id: "toolfk-editor",
    name: "ToolFK Editor",
    category: "Image Editing",
    url: "https://www.toolfk.com/tools/online-image-editor.html",
    description: "Crop/rotate/filters, free unlimited",
  },
  {
    id: "remove-bg",
    name: "Remove.bg",
    category: "Image Editing",
    url: "https://www.remove.bg/",
    description: "Background remover, limited free but unlimited low-res",
  },
  {
    id: "clipdrop",
    name: "Clipdrop",
    category: "Image Editing",
    url: "https://clipdrop.co/remove-background",
    description: "AI remover, no signup, unlimited free",
  },
  {
    id: "magic-remover",
    name: "Magic Studio",
    category: "Image Editing",
    url: "https://www.magicstudio.com/backgroundremover",
    description: "Free remover + edit, unlimited",
  },
  {
    id: "photoroom",
    name: "PhotoRoom",
    category: "Image Editing",
    url: "https://www.photoroom.com/background-remover",
    description: "Free editing, no signup, high quality",
  },
  {
    id: "pixlr",
    name: "Pixlr",
    category: "Image Editing",
    url: "https://pixlr.com/remove-background/",
    description: "AI remover, free tier unlimited",
  },
  {
    id: "slazzer",
    name: "Slazzer",
    category: "Image Editing",
    url: "https://www.slazzer.com/",
    description: "Auto remove, free limited but unlimited trials",
  },
  {
    id: "fotor",
    name: "Fotor",
    category: "Image Editing",
    url: "https://www.fotor.com/photo-editor/",
    description: "AI editor, free unlimited tools",
  },

  // AI Image Upscalers
  {
    id: "vectorink",
    name: "Vectorink",
    category: "Image Upscaling",
    url: "https://vectorink.io/en/upscaler",
    description: "Vector upscale, no signup, unlimited free",
  },
  {
    id: "imgupscaler",
    name: "ImgUpscaler",
    category: "Image Upscaling",
    url: "https://imgupscaler.ai/",
    description: "AI based, no signup, unlimited 4x",
  },
  {
    id: "image-upscaling",
    name: "Image Upscaling",
    category: "Image Upscaling",
    url: "https://image-upscaling.net/",
    description: "Free online, unlimited low-res",
  },
  {
    id: "imggen-upscale",
    name: "ImgGen",
    category: "Image Upscaling",
    url: "https://imggen.ai/tools/upscale-image",
    description: "Upscale + enhance, free unlimited",
  },
  {
    id: "cloudinary-upscale",
    name: "Cloudinary",
    category: "Image Upscaling",
    url: "https://cloudinary.com/tools/image-upscale",
    description: "Cloud based, free tier unlimited",
  },
  {
    id: "deepdream-upscaler",
    name: "DeepDream",
    category: "Image Upscaling",
    url: "https://deepdreamgenerator.com/blog/best-free-ai-image-upscaler-2026",
    description: "Guide + tools, free reference",
  },
  {
    id: "ninja-upscale",
    name: "Ninja",
    category: "Image Upscaling",
    url: "https://ninjatransfers.com/pages/upscale",
    description: "Printing focus, free unlimited",
  },
  {
    id: "imagefree-upscale",
    name: "ImageFree",
    category: "Image Upscaling",
    url: "https://imagefree.org/image-upscale",
    description: "Unlimited, no credits",
  },
  {
    id: "krea-upscaler",
    name: "Krea",
    category: "Image Upscaling",
    url: "https://www.krea.ai/features/ai-upscaler",
    description: "AI upscaler, free unlimited",
  },
  {
    id: "pixelbin-upscaler",
    name: "PixelBin",
    category: "Image Upscaling",
    url: "https://www.pixelbin.io/blog/best-ai-image-upscalers",
    description: "List + tools, free",
  },
  {
    id: "jaiportal-upscaler",
    name: "JaiPortal",
    category: "Image Upscaling",
    url: "https://www.jaiportal.com/free/ai-image-upscaler-free-tool",
    description: "Free tool, unlimited",
  },
  {
    id: "upsampler-upscale",
    name: "Upsampler",
    category: "Image Upscaling",
    url: "https://upsampler.com/free-image-upscaler-no-signup",
    description: "No signup, unlimited GPU",
  },
  {
    id: "webability-upscaler",
    name: "Webability",
    category: "Image Upscaling",
    url: "https://www.webability.io/tools/ai-image-upscaler",
    description: "Online free, unlimited",
  },
  {
    id: "vidguru-upscaler",
    name: "VidGuru",
    category: "Image Upscaling",
    url: "https://www.vidguru.ai/photo-enhancer",
    description: "Enhancer + upscale, free",
  },

  // AI Text Generation
  {
    id: "toolfk-text",
    name: "ToolFK Text Gen",
    category: "Text Generation",
    url: "https://www.toolfk.com/tools/online-text-generator.html",
    description: "AI content, no signup, unlimited",
  },
  {
    id: "writesonic",
    name: "Writesonic",
    category: "Text Generation",
    url: "https://writesonic.com/",
    description: "Free AI writing, brand tone, unlimited words",
  },
  {
    id: "jasper",
    name: "Jasper",
    category: "Text Generation",
    url: "https://www.jasper.ai/free-trial",
    description: "Free trial, content generation, unlimited ideas",
  },
  {
    id: "rytr",
    name: "Rytr",
    category: "Text Generation",
    url: "https://www.rytr.me/",
    description: "Unlimited free words, no signup",
  },
  {
    id: "simplified",
    name: "Simplified",
    category: "Text Generation",
    url: "https://www.simplified.com/ai-writer",
    description: "Free writer, multi-language",
  },
  {
    id: "gemini-text",
    name: "Gemini",
    category: "Text Generation",
    url: "https://gemini.google.com/",
    description: "Free text, unlimited prompts",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "Text Generation",
    url: "https://www.perplexity.ai/",
    description: "AI search + generation, free unlimited",
  },

  // AI Text Editing
  {
    id: "toolfk-text-editor",
    name: "ToolFK Text Editor",
    category: "Text Editing",
    url: "https://www.toolfk.com/tools/online-text-editor.html",
    description: "Free edit/conversion, unlimited",
  },
  {
    id: "quillbot",
    name: "Quillbot",
    category: "Text Editing",
    url: "https://www.quillbot.com/",
    description: "Free paraphraser, unlimited words",
  },
  {
    id: "grammarly",
    name: "Grammarly",
    category: "Text Editing",
    url: "https://www.grammarly.com/",
    description: "Free correction, unlimited",
  },
  {
    id: "reverso",
    name: "Reverso",
    category: "Text Editing",
    url: "https://www.reverso.net/text-translation",
    description: "Translation + edit, free unlimited",
  },
  {
    id: "wordtune",
    name: "Wordtune",
    category: "Text Editing",
    url: "https://www.wordtune.com/",
    description: "Free rewrite, unlimited",
  },

  // AI Text to Visual
  {
    id: "toolfk-ghibli",
    name: "ToolFK Ghibli",
    category: "Text to Visual",
    url: "https://www.toolfk.com/tools/ai-ghibli-style.html",
    description: "Text/photo to Ghibli art, free unlimited",
  },
  {
    id: "toolfk-lowpoly",
    name: "ToolFK Low Poly",
    category: "Text to Visual",
    url: "https://www.toolfk.com/tools/ai-low-poly.html",
    description: "Low-poly visuals, fun, unlimited",
  },
  {
    id: "toolfk-painting",
    name: "ToolFK Painting",
    category: "Text to Visual",
    url: "https://www.toolfk.com/tools/ai-photo-to-painting.html",
    description: "Van Gogh style, free",
  },
  {
    id: "toolfk-video",
    name: "ToolFK Img-to-Video",
    category: "Text to Visual",
    url: "https://www.toolfk.com/tools/online-img-to-video.html",
    description: "Animated conversion, unlimited",
  },
  {
    id: "artbreeder",
    name: "Artbreeder",
    category: "Text to Visual",
    url: "https://www.artbreeder.com/",
    description: "Text to art mix, free unlimited",
  },

  // AI Video Generators
  {
    id: "upsampler-video",
    name: "Upsampler",
    category: "Video Generation",
    url: "https://upsampler.com/free-video-generator-no-signup",
    description: "No signup, unlimited short video, no watermark",
  },
  {
    id: "veed-ai",
    name: "VEED",
    category: "Video Generation",
    url: "https://www.veed.io/tools/ai-video",
    description: "Veo/Kling models, free trial unlimited",
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    category: "Video Generation",
    url: "https://www.meta.ai/",
    description: "Animate/restyle, free no watermark",
  },
  {
    id: "grok-ai",
    name: "Grok",
    category: "Video Generation",
    url: "https://x.com/grok",
    description: "Free video/image, X par unlimited",
  },
  {
    id: "giz-ai",
    name: "Giz AI",
    category: "Video Generation",
    url: "https://www.giz.ai/ai-video-generator",
    description: "Face swap/text-to-video, no registration, unlimited",
  },
  {
    id: "dreamlux",
    name: "Dreamlux",
    category: "Video Generation",
    url: "https://dreamlux.ai/",
    description: "Online free, no watermark, unlimited",
  },
  {
    id: "vibess-ai",
    name: "Vibess",
    category: "Video Generation",
    url: "https://www.vibess.app/hu/features/ai-video-generator-free-no-watermark",
    description: "HD/4K, commercial use, free unlimited",
  },
  {
    id: "leonardo-veo",
    name: "Leonardo Veo",
    category: "Video Generation",
    url: "https://leonardo.ai/veo-3/",
    description: "Daily tokens, short clips unlimited",
  },
  {
    id: "pictory",
    name: "Pictory",
    category: "Video Generation",
    url: "https://pictory.ai/",
    description: "Script to video, free first round unlimited",
  },
  {
    id: "runwayml",
    name: "Runway",
    category: "Video Generation",
    url: "https://runwayml.com/",
    description: "Free credits, advanced editing unlimited",
  },
  {
    id: "capcut",
    name: "CapCut",
    category: "Video Generation",
    url: "https://www.capcut.com/",
    description: "No watermark free, social clips unlimited",
  },
  {
    id: "heygen",
    name: "HeyGen",
    category: "Video Generation",
    url: "https://www.heygen.com/",
    description: "AI avatars, free 3 video unlimited extend",
  },
  {
    id: "flexclip",
    name: "FlexClip",
    category: "Video Generation",
    url: "https://www.flexclip.com/",
    description: "Free 1080p, general editing unlimited",
  },
  {
    id: "jaiportal-video",
    name: "JaiPortal",
    category: "Video Generation",
    url: "https://www.jaiportal.com/free/ai-video-generator",
    description: "10 free credits, no subs unlimited",
  },
  {
    id: "vidau-ai",
    name: "Vidau",
    category: "Video Generation",
    url: "https://www.vidau.ai/free-ai-video-generators-with-no-watermark",
    description: "Local/open-source, unlimited",
  },
  {
    id: "easemate",
    name: "EaseMate",
    category: "Video Generation",
    url: "https://www.easemate.ai/ai-video-generator",
    description: "Text/image to video, free credits unlimited",
  },
  {
    id: "kapwing",
    name: "Kapwing",
    category: "Video Generation",
    url: "https://www.kapwing.com/ai-video-generator",
    description: "Basic free, unlimited shorts",
  },
  {
    id: "d-id",
    name: "D-ID",
    category: "Video Generation",
    url: "https://www.d-id.com/creative-reality-studio/",
    description: "Talking heads, free unlimited",
  },
  {
    id: "synthesia",
    name: "Synthesia",
    category: "Video Generation",
    url: "https://www.synthesia.io/",
    description: "Free trial, unlimited avatars",
  },
  {
    id: "lumen5",
    name: "Lumen5",
    category: "Video Generation",
    url: "https://lumen5.com/",
    description: "Free trial, script to video",
  },
  {
    id: "clipchamp",
    name: "ClipChamp",
    category: "Video Generation",
    url: "https://clipchamp.com/",
    description: "Free editing, Microsoft, unlimited",
  },
  {
    id: "fiddl-art",
    name: "Fiddl.art",
    category: "Video Generation",
    url: "https://fiddl.art/",
    description: "Missions for credits, unlimited video, new 2026",
  },
  {
    id: "pika-labs",
    name: "Pika Labs",
    category: "Video Generation",
    url: "https://pika.art/",
    description: "Text/image to video, free unlimited shorts",
  },
  {
    id: "vheer-ai",
    name: "Vheer",
    category: "Video Generation",
    url: "https://vheer.ai/",
    description: "Image-to-video, no signup unlimited",
  },

  // AI Music Generators
  {
    id: "remusic",
    name: "ReMusic",
    category: "Music Generation",
    url: "https://remusic.ai/ai-music-generator",
    description: "AI music, free unlimited",
  },
  {
    id: "aimusicgen",
    name: "AIMusicGen",
    category: "Music Generation",
    url: "https://aimusicgen.ai/",
    description: "Text to song, no signup",
  },
  {
    id: "easymusic",
    name: "EasyMusic",
    category: "Music Generation",
    url: "https://easymusic.ai/",
    description: "Simple generation, free unlimited",
  },
  {
    id: "soundverse",
    name: "Soundverse",
    category: "Music Generation",
    url: "https://www.soundverse.ai/blog/article/best-free-ai-music-generators",
    description: "Guide + tools, free",
  },
  {
    id: "musicmuse",
    name: "MusicMuse",
    category: "Music Generation",
    url: "https://www.musicmuse.ai/",
    description: "Creative tracks, unlimited",
  },
  {
    id: "tad-ai",
    name: "Tad",
    category: "Music Generation",
    url: "https://tad.ai/",
    description: "AI composer, free",
  },
  {
    id: "aimusic-so",
    name: "AIMusic.so",
    category: "Music Generation",
    url: "https://aimusic.so/",
    description: "Short clips, unlimited",
  },
  {
    id: "musichero",
    name: "MusicHero",
    category: "Music Generation",
    url: "https://musichero.ai/",
    description: "Hero-style, free",
  },

  // AI Voice/TTS (New Category)
  {
    id: "toolfk-tts",
    name: "ToolFK TTS",
    category: "Voice/TTS",
    url: "https://www.toolfk.com/tools/ai-text-to-speech.html",
    description: "Natural voice, no signup, unlimited",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "Voice/TTS",
    url: "https://elevenlabs.io/",
    description: "Voice cloning, free unlimited shorts",
  },
  {
    id: "naturalreaders",
    name: "NaturalReaders",
    category: "Voice/TTS",
    url: "https://www.naturalreaders.com/online/",
    description: "Free TTS, unlimited text",
  },
  {
    id: "speechify",
    name: "Speechify",
    category: "Voice/TTS",
    url: "https://www.speechify.com/",
    description: "Speed control, free unlimited",
  },
];